djangocat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
    path('weapon/upgrade/', views.weapon_upgrade, name='weapon_upgrade'),
]

postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'

urlpatterns = [
    path('', views.index, name='index'),
    path('info/', views.information, name="information"),
    path('postings/', views.posting_list, name='posting_list'),
    path('posting/create/', views.posting_create, name='posting_create'),
    path('posting/<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('posting/<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('posting/<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    path('posting/<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('posting/admin/create/', views.posting_admin_create, name='posting_admin_create'),
    path('posting/admin/delete/', views.posting_admin_delete, name='posting_admin_delete'),
]

postings/models.py
from django.db import models
from django.conf import settings

class Posting(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='postings')
    def __str__(self):
        posting_title = self.title
        if len(posting_title) > 10:
            posting_title = self.title[:10] + '...'
        return f'{posting_title} - 작성자:{self.author.username}'

class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='comment_list')
    content = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    def __str__(self):
        comment_content = self.content
        if len(comment_content) > 10:
            comment_content = self.content[:10] + '...'
        return f'{comment_content} - 작성자:{self.author.username}'

postings/forms.py
from django import forms
from .models import Posting, Comment

class PostingForm(forms.ModelForm):
    title = forms.CharField(label='제목', max_length=50)
    content = forms.CharField(label='내용', strip=False, widget=forms.Textarea)
    class Meta:
        model = Posting
        fields = ['title', 'content',]

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', max_length=300, strip=False, widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model = Comment
        fields = ['content',]

postings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Posting, Comment
from .forms import PostingForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator
from accounts.models import User

def index(request):
    return render(request, 'postings/index.html')

def information(request):
    return render(request, 'postings/information.html')

def posting_list(request):
    postings = Posting.objects.order_by('date').reverse()
    postings_num = postings.count()
    if postings_num == 0:
        context = {
            'postings_num': postings_num,
            'move_previous': False,
            'move_next': False,
            'page_range': [1],
            'page_postings': None,
        }
        return render(request, 'postings/posting_list.html', context)

    paginator = Paginator(postings, 10)

    page = request.GET.get('page')
    if page == None:
        page = '1'
    elif page == '0' or not page.isdecimal():
        return render(request, '404.html')

    count = 5
    recent_page = int(page)
    
    last_page = postings_num // 10
    if postings_num % 10 != 0:
        last_page += 1
    if recent_page > last_page:
        return render(request, '404.html')
    
    previous_page = ((recent_page-1)//count)*count
    move_previous = True
    if previous_page < count:
        move_previous = False
    
    next_page = ((recent_page-1)//count+1)*count+1
    move_next = True
    if next_page > last_page:
        move_next = False
    
    start_page = previous_page+1
    end_page = next_page-1
    if end_page > last_page:
        end_page = last_page

    page_range = list(range(start_page, end_page+1))
    page_postings = paginator.get_page(page)

    page_postings_start_index = postings_num-(recent_page-1)*10

    context = {
        'postings_num': postings_num,
        'last_page': last_page,
        'previous_page': previous_page,
        'move_previous': move_previous,
        'next_page': next_page,
        'move_next': move_next,
        'page_range': page_range,
        'page_postings': page_postings,
        'page_postings_start_index': page_postings_start_index,
    }
    return render(request, 'postings/posting_list.html', context)

def posting_create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            posting_form = PostingForm(request.POST)
            
            if posting_form.is_valid():
                posting_form = posting_form.save(commit=False)
                posting_form.author = request.user
                posting_form.save()
                return redirect('postings:posting_list')
        else:
            posting_form = PostingForm()
        
        context = {
            'posting_type': '글쓰기',
            'posting_form': posting_form,
        }
        return render(request, 'postings/posting_form.html', context)
    return redirect('accounts:login')

def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment_form = comment_form.save(commit=False)
            comment_form.posting = posting
            comment_form.author = request.user
            comment_form.save()
            return redirect('postings:posting_detail', posting_id)
    else :
        comment_form = CommentForm()
    
    comments = posting.comment_list.all()

    context = {
        'posting': posting,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'postings/posting_detail.html', context)

@login_required
def posting_update(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if posting.author == request.user:
        if request.method == 'POST':
            posting_form = PostingForm(request.POST, instance=posting)

            if posting_form.is_valid():
                posting_form.save()
                return redirect('postings:posting_detail', posting_id)
        else:
            posting_form = PostingForm(instance=posting)

        context = {
            'posting_type': '글수정',
            'posting': posting,
            'posting_form': posting_form,
        }
        return render(request, 'postings/posting_form.html', context)
    return redirect('postings:posting_detail', posting_id)

@login_required
@require_POST
def posting_delete(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if posting.author == request.user:
        posting.delete()
        return redirect('postings:posting_list')
    return redirect('postings:posting_detail', posting_id)

@login_required
@require_POST
def comment_delete(request, posting_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author == request.user:
        comment.delete()
    return redirect('postings:posting_detail', posting_id)

@login_required
@staff_member_required
def posting_admin_create(request):
    posting_index = Posting.objects.all().count() + 1
    for i in range(10):
        Posting.objects.create(
            title = f'연습용 데이터({posting_index})입니다.',
            content = f'{i}번 글입니다.',
            author = request.user
        )
        posting_index += 1
    return redirect('postings:posting_list')

@login_required
@staff_member_required
def posting_admin_delete(request):
    Posting.objects.filter(author__is_staff=True, title__contains='연습용').delete()
    return redirect('postings:posting_list')

postings/templates/postings/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/index.css' %}">
{% endblock %}

{% block body %}
  <h1>메인 페이지</h1>

  <p>웹 페이지의 주요 기능을 소개합니다!</p>
  <ol>
    <li class="posting__list__text">가입해서 글과 댓글을 작성할 수 있어요.</li>
    <li class="posting__list__text">그리고 간단한 웹 게임을 즐길 수 있어요.</li>
  </ol>

  <div class="posting__profile">
    <img class="posting__profile__img" src="{% static 'images/rabbit.png' %}" alt="rabbit">
    <div class="posting__profile__info">
      <div class="posting__profile__info__title">About Me</div>
      <div class="posting__profile__info__text">🍊 Name: 김규리</div>
      <div class="posting__profile__info__text">📧 Email: samicoding@gmail.com</div>
      <div class="posting__profile__info__text">🐈‍⬛ Github: <a href="https://github.com/SamiCoding" target="_blank">깃허브 방문하기</a></div>
      <div class="posting__profile__info__text">❓더 많은 정보를 원하시나요? <a href="{% url 'postings:information' %}">여기</a>를 눌러보세요.</div>
    </div>
  </div>

{% endblock %}

postings/templates/postings/information.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/information.css' %}">
{% endblock %}

{% block body %}
  <h1>안녕하세요,</h1>
  <h1>웹 개발을 좋아하는 김규리 입니다!</h1>
  <h3>→ 저는 <span class="highlight">새로운 것을 배우기</span>를 좋아합니다.</h3>
  <h3>→ 그리고 좋아하는 일에 <span class="highlight">열정</span>이 넘치며, 주어진 일을 완성하기 위해 <span class="highlight">끝까지 최선</span>을 다합니다.</h3>

  <br>

  <h2>🍊 연락처 및 정보</h2>
  <p>📧 Email: samicoding@gmail.com</p>
  <p>🐈‍⬛ Github: <a href="https://github.com/SamiCoding" target="_blank">깃허브 방문하기</a></p>
  <div>

  </div>

  <br>
  
  <h2>🛠️ 기술 스택</h2>
  <div class="stacks">
    <div class="stacks__category">
      <h3>Frontend</h3>
      <div>- HTML, CSS</div>
      <div>- JavaScript</div>
      <div>- Vue.js</div>
      <div>- React</div>
    </div>
    <div class="stacks__category">
      <h3>Backend</h3>
      <div>- Python</div>
      <div>- Django</div>
      <div>- PostgreSQL</div>
      <div>- SQLite</div>
    </div>
    <div class="stacks__category">
      <h3>Deployment</h3>
      <div>- Heroku</div>
      <div>- Vercel</div>
      <div>- Railway</div>
      <div>- AWS</div>
    </div>
    <div class="stacks__category">
      <h3>Version Control</h3>
      <div>- Git</div>
      <div>- GitHub</div>
      <div>- GitLab</div>
    </div>
  </div>

  <br>

  <h2>💻 프로젝트</h2>
  <div class="project">
    <h3 class="project__title">장고캣</h3>
    <div class="project__info">
      <span class="project__info__text">깃허브 : </span>
      <a href="https://github.com/SamiCoding/django-cat-project" target="_blank">깃허브로 이동</a>
    </div>
    <div class="project__info">
      <span class="project__info__text">웹 사이트 : </span>
      <a href="https://samicoding.pythonanywhere.com/" target="_blank">프로젝트로 이동</a>
    </div>
    <div class="project__progress">
      <span>1차 진행(개별) : 2022.09 ~ 2022.11</span>
      <span>2차 진행(개별) : 2023.10 ~ 2023.11</span>
    </div>
    <div class="project__image_box">
      <img class="project__image" src="{% static 'images/project1-1.png' %}" alt="project1-1">
      <img class="project__image" src="{% static 'images/project1-2.png' %}" alt="project1-2">
    </div>
    <div class="project__content">
      <p>
        <span>&nbsp;&nbsp;“장고캣”은 게시판 기능을 가진 간단한 웹 사이트 입니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;코딩 학원에서 근무할 때 수업용으로 만들었던 웹 사이트 입니다.</span>
        <span>학생들이 배운 Python을 활용할 수 있도록 웹 프레임워크를 Django로 선택하였습니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;CRUD를 기본으로 하는 글과 댓글 작성이 가능한 게시판을 메인으로 하였습니다.</span>
        <span>그리고 학생들이 재밌게 즐길 수 있도록 간단한 웹 게임 컨텐츠를 추가하여 스스로 코딩해볼 수 있도록 만들었습니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;이 웹 사이트를 포트폴리오로 활용하기 위해 페이지를 추가하였습니다.</span>
        <span>게임 목록에 “그려줘 친구들!”을 추가하여 다양한 게임을 즐길 수 있도록 하였습니다.</span>
      </p>
      <div class="project__stack">
        <div>Frontend : Django Templates</div>
        <div>Backend : Django</div>
        <div>Database : SQLite</div>
        <div>Deployment : PythonAnywhere</div>
      </div>
    </div>
  </div>

  <div class="project">
    <h3 class="project__title">그려줘 친구들!</h3>
    <div class="project__info">
      <span class="project__info__text">웹 사이트 : </span>
      <a href="https://draw-it-friends.vercel.app/" target="_blank">프로젝트로 이동</a>
    </div>
    <div class="project__progress">
      <span>1차 진행(팀) : 2020.05 ~ 2020.06</span>
      <span>2차 진행(개별) : 2023.07 ~ 2023.09</span>
    </div>
    <div class="project__image_box">
      <img class="project__image" src="{% static 'images/project2-1.jpg' %}" alt="project2-1">
      <img class="project__image" src="{% static 'images/project2-2.jpg' %}" alt="project2-2">
    </div>
    <div class="project__content">
      <p>
        <span>&nbsp;&nbsp;“그려줘 친구들!”은 인공지능을 활용한 아동 교육용 게임입니다.</span>
        <span>아이들이 직접 그림을 그리면서 동화에 참여하는 느낌을 줄 수 있도록 만들었습니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;SSAFY에서 위 프로젝트를 처음 진행할 당시 프론트엔드를 맡았습니다.</span>
        <span>이야기를 등록하는 관리자 페이지, 게임 진행 그리고 게임을 통해 그려진 작품들을 볼 수 있는 마이페이지 기능을 구현하였습니다.</span>
        <span>Jira를 사용해서 팀원들과 프로젝트 진행 상항을 공유하였고, Git을 이용하여 협업했습니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;이후 웹 사이트에 새로운 기능을 추가하기 위해 개별적으로 프로젝트를 진행하였습니다.</span>
        <span>작품 꾸미기 등의 기능을 추가하기 위해 이전에는 담당하지 않았던 백엔드도 함께 다루었습니다.</span>
      </p>
      {% comment %} <p>
        <span>&nbsp;&nbsp;처음 프로젝트를 진행할 당시에는 기능 구현을 중점으로 두었다면, 두 번째로 진행할 때는 효율적으로 코드를 작성하기 위해 노력하였습니다.</span>
        <span>무료 서버를 사용하면서 데이터를 불러올 때 딜레이가 발생하였는데, 데이터를 불러오는 동안 로딩화면이 보여질 수 있도록 만들었습니다.</span>
      </p> {% endcomment %}
      <div class="project__stack">
        <div>Frontend : Vue.js, Vuetify</div>
        <div>Backend : Django</div>
        <div>Database : PostgreSQL</div>
        <div>Deployment : Vercel(Frontend), Railway(Backend)</div>
      </div>
    </div>
  </div>

  <div class="project">
    <h3 class="project__title">슬기로운 음식처방</h3>
    <div class="project__progress">
      <span>진행(팀) : 2020.03 ~ 2020.04</span>
    </div>
    <div class="project__image_box">
      <img class="project__image project__image--border" src="{% static 'images/project3-1.png' %}" alt="project3-1">
      <img class="project__image project__image--border" src="{% static 'images/project3-2.png' %}" alt="project3-2">
    </div>
    <div class="project__content">
      <p>
        <span>&nbsp;&nbsp;“슬기로운 음식처방”은 사용자의 건강상태와 맞는 음식점을 동의보감 데이터를 활용해 추천해주는 웹 사이트 입니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;KNN 알고리즘을 이용해 사용자에게 필요한 재료에 해당하는 음식점을 추천해 주도록 구현하였습니다.</span>
        <span>그리고 KoNLPy를 활용하여 음식점의 댓글을 분석 후 음식점에 대한 키워드를 추출하였습니다.</span>
      </p>
      <div class="project__stack">
        <div>Frontend : Vue.js, Vuetify</div>
        <div>Backend : Django</div>
        <div>Database : SQLite</div>
        <div>Deployment : AWS</div>
      </div>
    </div>
  </div>

  <div class="project">
    <h3 class="project__title">Vote Us</h3>
    <div class="project__progress">
      <span>진행(팀) : 2020.01 ~ 2020.02</span>
    </div>
    <div class="project__image_box">
      <img class="project__image project__image--border" src="{% static 'images/project4-1.jpg' %}" alt="project4-1">
    </div>
    <div class="project__content">
      <p>
        <span>&nbsp;&nbsp;“Vote Us”는 사용자가 얼굴인식과 지문인식을 통한 인증을 완료한 후 투표를 할 수 있도록 구현한 웹 사이트 입니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;새로운 경험을 위해 지금까지 사용해보지 않았던 React를 사용해 보았습니다.</span>
        <span>카메라와 지문 센서를 이용하여 사용자의 얼굴과 지문 정보 얻은 후 데이터를 Flask로 전달하도록 구현하였습니다.</span>
        <span>그리고 본인인증을 완료한 이후 투표 기능이 활성화되도록 만들었습니다.</span>
      </p>
      <div class="project__stack">
        <div>Frontend : React</div>
      </div>
    </div>
  </div>

  <div class="project">
    <h3 class="project__title">청각장애인을 위한 소리 시각화 안경</h3>
    <div class="project__progress">
      <span>진행(팀) : 2018.03 ~ 2018.11</span>
    </div>
    <div class="project__image_box">
      <img class="project__image project__image--border" src="{% static 'images/project5-1.JPG' %}" alt="project5-1">
      <img class="project__image project__image--border" src="{% static 'images/project5-2.JPG' %}" alt="project5-2">
    </div>
    <div class="project__content">
      <p>
        <span>&nbsp;&nbsp;“청각장애인을 위한 소리 시각화 안경”은 주변의 소리를 시각화 해서 보여주는 역할을 하는 장치입니다.</span>
        <span>청각장애인 주변의 위험한 상황을 감지하여 일상 생활에 도움이 될 수 있도록 구현해 보았습니다.</span>
      </p>
      <p>
        <span>&nbsp;&nbsp;대학교 4학년, 캡스톤디자인으로 위 프로젝트를 시작하게 되었습니다.</span>
        <span>프로젝트를 통해 TensorFlow 모듈을 처음 사용해 보았고, 코딩에 대한 관심을 처음 갖게 된 계기가 되었습니다.</span>
      </p>
      <div class="project__stack">
        <div>개발 환경 : Tinker Board</div>
        <div>Library : TensorFlow</div>
      </div>
    </div>
  </div>

  <br>

  <h2>💼 경력사항</h2>
  <div class="education">
    <h3>→ 씨큐브코딩 중계센터 강사</h3>
    <div class="education_date">2021.05 ~ 2023.02</div>
  </div>
  <div class="education_info">&nbsp;&nbsp;스크래치, S4A, 앱인벤터 등의 블록 코딩부터 Python, AI, Django 등의 텍스트 코딩까지 다양한 수업을 진행하였습니다.</div>

  <br>

  <h2>✏️ 교육과정</h2>
  <div class="education">
    <h3>→ 삼성 청년 SW 아카데미(SSAFY) 2기</h3>
    <div class="education_date">2019.07 ~ 2020.06</div>
  </div>
  <div class="education_info">&nbsp;&nbsp;Python, Django, JavaScript, Vue.js 등 SW 필수 지식 및 알고리즘 중심의 코딩 교육을 바탕으로 SW 프로젝트를 수행하였습니다.</div>

  <br>

  <h2>🏆 수상내역</h2>
  <div class="awards">
    <h3>→ SSAFY 심화 프로젝트 결선 발표회 1등</h3>
    <div class="awards_date">2020.06</div>
  </div>
  <div class="awards">
    <h3>→ SSAFY 심화 프로젝트 본선 발표회 1등 (광주 1등)</h3>
    <div class="awards_date">2020.06</div>
  </div>
  <div class="awards">
    <h3>→ SSAFY 빅데이터 특화 프로젝트 광주 1반 1등</h3>
    <div class="awards_date">2020.05</div>
  </div>
  <div class="awards">
    <h3>→ LINC+ 전국 캡스톤디자인 경진대회 대상</h3>
    <div class="awards_date">2018.11</div>
  </div>


{% endblock %}

postings/templates/postings/posting_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/posting_detail.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 보기</h1>

  <div class="posting">
    <table class="posting__detail">
      <tr>
        <td class="posting__detail__title">{{posting.title}}</td>
      </tr>
      <tr>
        <td class="posting__detail__date">
          <span class="author">작성자: {{posting.author.username}}</span>
          <span class="division">&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;</span>
          <span class="date">작성일 : {{posting.date|date:'Y-m-d A f'}}</span>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__content">
          <div class="content">
            <span class="content__space">{{posting.content|linebreaksbr}}</span>
          </div>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__function transparent">
          <div>
            {% if posting.author.username == user.username %}
              <a class="button" href="{% url 'postings:posting_update' posting.id %}">수정</a>
              <form action="{% url 'postings:posting_delete' posting.id %}" method="post" onsubmit="return contentDelete()">
                {% csrf_token %}
                <input class="button" type="submit" value="삭제">
              </form>
            {% endif %}
            <a class="button" href="{% url 'postings:posting_list' %}">글 목록</a>
          </div>
        </td>
      </tr>
    </table>

    <table class="posting__comment">
      <tr>
        <th>댓글 목록</th>
      </tr>
      {% if user.is_authenticated %}
        <tr>
          <td class="posting__comment__create">
            <form action="" method="post">
              {% csrf_token %}
              <div>
                {{comment_form.as_div}}
                <input class="button" type="submit" value="작성">
              </div>
            </form>
          </td>
        </tr>
      {% endif %}
      {% for comment in comments %}
        <tr>
          <td class="posting__comment__content">
            <div>
              <span class="content__space">{{comment.content|linebreaksbr}}</span>
              <div class="posting__comment__delete">
                {% if comment.author.username == user.username %}
                  <form action="{% url 'postings:comment_delete' posting_id=posting.id comment_id=comment.id %}" method="post" onsubmit="return contentDelete()">
                    {% csrf_token %}
                    <input type="submit" value="x">
                  </form>
                {% endif %}
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date">
            <span class="author">{{comment.author.username}}</span>
            <span class="division">&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;</span>
            <span class="date">{{comment.date|date:'Y-m-d A f'}}</span>
          </td>
        </tr>
        <tr>
          <td>
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="posting__comment__content">
            댓글이 아직 작성되지 않았습니다.
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date"></td>
        </tr>
        <tr>
          <td>
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

  <script>
    const contents = document.getElementsByClassName("content__space")
    
    for (let i=0; i<contents.length; i++) {
      contents[i].innerHTML = contents[i].innerHTML.replace(/ /g, "&nbsp;");
    }

    function contentDelete() {
      const result = confirm("삭제하시겠습니까?");
      return result;
    }
  </script>
{% endblock %}

postings/templates/postings/posting_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/posting_form.css' %}">
{% endblock %}

{% block body %}
  <h1>{{posting_type}}</h1>

  <div class="posting-form">
    <form action="" method="post">
      {% csrf_token %}
      {{posting_form.as_p}}
  
      <div class="posting-form__function--bottom">
        {% if posting %}
          <a class="button" href="{% url 'postings:posting_detail' posting.id %}">취소</a>
        {% endif %}
        <input class="button" type="submit" value="등록">
      </div>
    </form>
  </div>
{% endblock %}

postings/templates/postings/posting_list.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/postings/posting_list.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="posting">
    <div class="posting__function--top">
      {% if request.user.is_staff %}
        <a class="button" href="{% url 'postings:posting_admin_create' %}">연습용 데이터 생성(관리자)</a>
        <a class="button" href="{% url 'postings:posting_admin_delete' %}">연습용 데이터 삭제(관리자)</a>
      {% endif %}
      <a class="button" href="{% url 'postings:posting_create' %}">글쓰기</a>
    </div>
  
    <table class="posting__list">
      <tr>
        <th class="index">번호</th>
        <th class="title">제목</th>
        <th class="author">작성자</th>
        <th class="date">날짜</th>
      </tr>
      {% for posting in page_postings %}
        <tr>
          <td class="index">{{page_postings_start_index|sub:forloop.counter0}}</td>
          <td class="title">
            <a class="title-content" href="{% url 'postings:posting_detail' posting.id %}">{{posting.title}}</a>
            <a href="{% url 'postings:posting_detail' posting.id %}"><span class="comment-number">[{{posting.comment_list.count}}]</span></a>
          </td>
          <td class="author-content">{{posting.author.username}}</td>
          <td class="date">{{posting.date|date:'Y-m-d'}}</td>
        </tr>
      {% empty %}
        <tr>
          <td class="index">-</td>
          <td class="title">글을 작성해주세요.</td>
          <td class="author">-</td>
          <td class="date">-</td>
        </tr>
      {% endfor %}
    </table>

    <p class="paginator">
      {% if page_postings.number == 1 %}
        <a class="paginator__disabled" disabled>처음</a>
      {% elif postings_num == 0 %}
        <a class="paginator__disabled" disabled>처음</a>
      {% else %}
        <a href="?page=1">처음</a>
      {% endif %}

      {% if move_previous %}
        <a href="?page={{previous_page}}">이전</a>
      {% else %}
        <a class="paginator__disabled" disabled>이전</a>
      {% endif %}

      {% for page_number in page_range %}
        {% if page_number == page_postings.number %}
          <a class="page_number__active" href="?page={{page_number}}">{{page_number}}</a>
        {% else %}
          <a class="page_number" href="?page={{page_number}}">{{page_number}}</a>
        {% endif %}
      {% endfor %}

      {% if move_next %}
        <a href="?page={{next_page}}">다음</a>
      {% else %}
        <a class="paginator__disabled" disabled>다음</a>
      {% endif %}

      {% if page_postings.number == page_postings.paginator.num_pages %}
        <a class="paginator__disabled" disabled>끝</a>
      {% else %}
        <a href="?page={{last_page}}">끝</a>
      {% endif %}
    </p>
  </div>
{% endblock %}