djangocat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
    path('weapon/upgrade/', views.weapon_upgrade, name='weapon_upgrade'),
]

games/models.py
from django.db import models
from django.conf import settings

class Event(models.Model):
    order = models.IntegerField()
    title = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    def __str__(self):
        if self.active:
            return f'{self.order}. {self.title} (개최중)'
        else:
            return f'{self.order}. {self.title} (종료)'

class DefaultLuckyItem(models.Model):
    name = models.CharField(max_length=20)
    power = models.IntegerField()
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, related_name='default_lucky_item_list', null=True, blank=True)
    max_level = models.IntegerField(default=3)
    def __str__(self):
        lucky_item_name = self.name
        if self.event :
            lucky_item_name += '(이벤트)'
        return f'{lucky_item_name} - 공격력:{self.power}'

class LuckyItem(models.Model):
    default_lucky_item = models.ForeignKey(DefaultLuckyItem, on_delete=models.SET_NULL, related_name='lucky_item_list', null=True, blank=True)
    power = models.IntegerField()
    level = models.IntegerField(default=1)
    def __str__(self):
        return f'{self.default_lucky_item.name}.LV{self.level}'

class DefaultWeapon(models.Model):
    name = models.CharField(max_length=20)
    power = models.IntegerField()
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, related_name='default_weapon_list', null=True, blank=True)
    def __str__(self):
        weapon_name = self.name
        if self.event :
            weapon_name += '(이벤트)'
        return f'{weapon_name} - 공격력:{self.power}'

class Weapon(models.Model):
    default_weapon = models.ForeignKey(DefaultWeapon, on_delete=models.SET_NULL, related_name='weapon_list', null=True, blank=True)
    power = models.IntegerField()
    level = models.IntegerField(default=1)
    def __str__(self):
        return f'{self.default_weapon.name}.LV{self.level}'

class Character(models.Model):
    nickname = models.CharField(max_length=20)
    weapon = models.OneToOneField(Weapon, on_delete=models.SET_NULL, related_name='character_who_have', null=True, blank=True)
    coin = models.BigIntegerField(default = 0)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='character', null=True, blank=True)
    inventory = models.ManyToManyField(LuckyItem, related_name='characters_who_have', blank=True)
    def __str__(self):
        return f'{self.nickname} - {self.user.username}'

class Enemy(models.Model):
    name = models.CharField(max_length=20)
    level = models.IntegerField(default=1)
    hp = models.IntegerField()
    def __str__(self):
        return f'{self.name}.LV{self.level}'

games/forms.py
from django import forms
from .models import Character

class CharacterForm(forms.ModelForm):
    nickname = forms.CharField(label="닉네임을 입력해주세요", max_length=20)
    class Meta:
        model = Character
        fields = ['nickname',]

games/views.py
from django.shortcuts import render, redirect, get_object_or_404
from random import *
from .models import Event, DefaultLuckyItem, LuckyItem, DefaultWeapon, Weapon, Character, Enemy
from .forms import CharacterForm
from django.views.decorators.http import require_POST
from django.db.models import Sum

def default_lucky_item_generate():
    lucky_items = {
        '삼각김밥': 2,
        '라면': 5,
        '떡볶이': 8,
        '치킨': 10,
    }
    for lucky_item_name, lucky_item_power in lucky_items.items():
        if DefaultLuckyItem.objects.filter(name=lucky_item_name).count() == 0:
            DefaultLuckyItem.objects.create(
                name = lucky_item_name,
                power = lucky_item_power,
            )

def default_weapon_generate():
    weapons = {
        '주먹도끼': 2,
        '가벼운 물총': 3,
        '낡은 검': 5,
        '수상한 막대기': 7,
        '수학의 정석': 9,
    }
    for weapon_name, weapon_power in weapons.items():
        if DefaultWeapon.objects.filter(name=weapon_name).count() == 0:
            DefaultWeapon.objects.create(
                name = weapon_name,
                power = weapon_power,
            )

def default_enemy_generate():
    enemies = {
        # 종이 시리즈
        '흩날리는 종이': [1, 10],
        '흩날리는 유인물': [1, 15],
        '흩날리는 학습지': [2, 30],
        '흩날리는 시험지': [2, 100],
        '중간고사': [3, 330],
        '기말고사': [4, 440],
        '모의고사': [5, 550],
        '대학수학능력시험': [7, 770],
        '전공시험': [9, 990],
        '졸업논문': [10, 1500],

        # 과제 시리즈
        '수행평가': [3, 250],
        '개별과제': [8, 750],
        '조별과제': [8, 1000],

        # 공식 시리즈
        '국어 문법': [1, 80],
        '수학 공식': [1, 85],
        '영어 문법': [1, 85],
        '피타고라스 정리': [2, 165],
        '이진법': [2, 175],
        '옴의 법칙': [2, 185],
        '미적분': [5, 485],
        
        # 주방용품 시리즈
        '뒤집어진 냄비': [1, 25],
        '코팅이 벗겨진 후라이팬': [2, 125],
        '비어있는 냄비': [3, 225],
        '코팅 후라이팬': [4, 325],
        '달궈진 후라이팬': [5, 425],
        '끓고있는 냄비': [5, 445],

        # 버섯 시리즈
        '수수한 독버섯': [1, 50],
        '화려한 독버섯': [2, 150],
        
        # 용 시리즈
        '아기 용': [1, 100],
        '드래곤 헤츨링': [3, 300],
        '성룡': [6, 600],
        '투명 드래곤': [8, 800],
        '고대룡': [10, 1000],
    }
    for enemy_name, enemy_info in enemies.items():
        if Enemy.objects.filter(name=enemy_name).count() == 0:
            Enemy.objects.create(
                name = enemy_name,
                level = enemy_info[0],
                hp = enemy_info[1],
            )

def default_event_generate():
    if Event.objects.all().count() == 0:
        event_order = 1
    else:
        latest_event = Event.objects.last()
        event_order = latest_event.order + 1

    events_and_lucky_items = {
        '오픈 기념 이벤트': [
            True,
            {
                '행운의 꽃다발': [1, 50],
            },
        ],
        '수능 이벤트': [
            False,
            {
                '수능 샤프': [1, 30],
            },
        ],
    }

    for event_title, event_lucky_items in events_and_lucky_items.items():
        if Event.objects.filter(title=event_title).count() == 0:
            Event.objects.create(
                order = event_order,
                title = event_title,
                active = event_lucky_items[0],
            )
            event_order += 1
        
        event = Event.objects.get(title=event_title)
        for event_lucky_item_name, event_lucky_item_info in event_lucky_items[1].items():
            if DefaultLuckyItem.objects.filter(event__title=event_title, name=event_lucky_item_name).count() == 0:
                DefaultLuckyItem.objects.create(
                    name = event_lucky_item_name,
                    power = event_lucky_item_info[1],
                    event = event,
                    max_level = event_lucky_item_info[0],
                )

def game_list(request):
    default_lucky_item_generate()
    default_weapon_generate()
    default_enemy_generate()
    default_event_generate()
    return render(request, 'games/game_list.html')

def adventure_home(request):
    # 로그인 한 경우
    if request.user.is_authenticated:
        # 생성한 캐릭터가 없을 경우
        if Character.objects.filter(user=request.user).count() == 0:
            if request.method == 'POST':
                character_form = CharacterForm(request.POST)
                character_form = character_form.save(commit=False)
                character_form.user = request.user
                character_form.save()
                return redirect('games:adventure_home')
            else:
                character_form = CharacterForm()
            context = {
                'character_form': character_form,
            }
            return render(request, 'games/character_form.html', context)
        # 생성한 캐릭터가 있는 경우
        else:
            character = get_object_or_404(Character, user=request.user)
            # 무기를 얻지 못한 경우
            if character.weapon == None:
                # 무기 랜덤 선택
                random_weapon = DefaultWeapon.objects.filter(event=None).order_by('?')[0]
                context = {
                    'random_weapon': random_weapon,
                }
                return render(request, 'games/adventure_new.html', context)
            # 무기를 얻은 경우
            else:
                context = {
                    'character': character,
                    'weapon_name': character.weapon.default_weapon.name,
                    'weapon_power': character.weapon.power,
                }
                return render(request, 'games/adventure_home.html', context)
    # 로그인 하지 않은 경우
    else:
        return redirect('accounts:login')

@require_POST
def weapon_get(request):
    character = get_object_or_404(Character, user=request.user)

    weapon_id = request.POST.get('random-weapon')
    selected_weapon = get_object_or_404(DefaultWeapon, id=weapon_id)

    weapon = Weapon.objects.create(
        default_weapon = selected_weapon,
        power = selected_weapon.power
    )
    
    character.weapon = weapon
    character.save()
    return redirect('games:adventure_home')

def adventure_attack(request):
    character = get_object_or_404(Character, user=request.user)
    character_weapon_level = character.weapon.level
    random_enemy = Enemy.objects.filter(level__lte=character_weapon_level).order_by('?')[0]
    
    context = {
        'random_enemy': random_enemy,
    }
    return render(request, 'games/adventure_attack.html', context)

@require_POST
def adventure_attack_result(request):
    character = get_object_or_404(Character, user=request.user)

    enemy_id = request.POST.get('random-enemy')
    enemy = get_object_or_404(Enemy, id=enemy_id)

    if character.weapon.power*10 >= enemy.hp:
        result = '승리'
        reward_coin = randint(enemy.hp*10-enemy.level*5, enemy.hp*10+enemy.level*5)
        character.coin += reward_coin
        character.save()
    else:
        result = '패배'
        reward_coin = 0
    
    context = {
        'enemy': enemy,
        'result': result,
        'reward_coin' : reward_coin,
    }
    return render(request, 'games/adventure_attack_result.html', context)

def weapon_workroom(request):
    character = get_object_or_404(Character, user=request.user)

    # 무기 강화에 필요한 코인 계산 (무기 레벨에 따라 증가)
    required_coin = character.weapon.level*1000

    inventory = character.inventory.all()

    original_power = character.weapon.power
    additional_power = inventory.aggregate(Sum('power'))['power__sum']
    if additional_power == None:
        additional_power = 0

    context = {
        'character': character,
        'weapon_name': character.weapon.default_weapon.name,
        'weapon_level': character.weapon.level,
        'weapon_power': original_power + additional_power,
        'inventory': inventory,
        'original_power': original_power,
        'additional_power': additional_power,
        'required_coin': required_coin,
    }
    return render(request, 'games/weapon_workroom.html', context)

@require_POST
def weapon_pick(request):
    character = get_object_or_404(Character, user=request.user)
    # 캐릭터가 갖고 있는 코인 저장
    character_coin = character.coin
    
    # 캐릭터가 500코인 이상 갖고 있는 경우
    if character_coin >= 500:
        # 500코인 소모
        character.coin = character_coin - 500
        character.save()

        inventory = character.inventory.all()

        original_power = character.weapon.power
        additional_power = inventory.aggregate(Sum('power'))['power__sum']
        if additional_power == None:
            additional_power = 0

        context = {
            'character': character,
            'weapon_name': character.weapon.default_weapon.name,
            'weapon_level': character.weapon.level,
            'weapon_power': original_power + additional_power,
            'inventory': inventory,
            'original_power': original_power,
            'additional_power': additional_power,
        }

        result = choices(['무기', '아이템'], [9, 1])[0]
        get_event = choices([True, False], [3, 7])[0]
        if result == '무기':
            if Event.objects.filter(active=True).count() != 0 and get_event == True and DefaultWeapon.objects.filter(event__active=True).count() != 0:
                random_weapon = DefaultWeapon.objects.filter(event__active=True).order_by('?')[0]
            else:
                random_weapon = DefaultWeapon.objects.filter(event=None).order_by('?')[0]
            context['random_weapon'] = random_weapon
            print(context)
            return render(request, 'games/weapon_change.html', context)
        else:
            if Event.objects.filter(active=True).count() != 0 and get_event == True and DefaultLuckyItem.objects.filter(event__active=True).count() != 0:
                default_random_lucky_item = DefaultLuckyItem.objects.filter(event__active=True).order_by('?')[0]
            else:
                default_random_lucky_item = DefaultLuckyItem.objects.filter(event=None).order_by('?')[0]
            

games/templates/games/adventure_attack.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <div class="adventure">
    <h1>모험을 떠났습니다.</h1>
    <p>당신은 '{{random_enemy.name}}'을(를) 만났습니다.</p>

    <p>
      <img src="{% static 'images/cat_adventure_surprise.png' %}" alt="cat_adventure_surprise">
    </p>
    
    <p>
      <form action="{% url 'games:adventure_attack_result' %}" method="post">
        {% csrf_token %}
        <button type="submit" name="random-enemy" value="{{random_enemy.id}}">공격하기</button>
      </form>
    </p>
  
    <p>
      <button onclick="goBack()">도망치기</button>
    </p>
  </div>

  <script>
    function goBack() {
      const url = "{% url 'games:adventure_home' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/adventure_attack_result.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <div class="adventure">
    <h1>전투 결과</h1>
    <p>당신은 '{{enemy.name}}'와(과)의 전투에서 {{result}}하였습니다.</p>
  
    {% if result == "승리" %}
    <p>{{reward_coin}}코인을 획득하셨습니다.</p>
    
    <p>
      <img src="{% static 'images/cat_adventure_win.png' %}" alt="cat_adventure_win">
    </p>
    {% else %}
      <p>
        <img src="{% static 'images/cat_adventure_lose.png' %}" alt="cat_adventure_lose">
      </p>
    {% endif %}
    <p>
      <button onclick="goAdventure()">모험 떠나기</button>
    </p>
    <p>
      <button onclick="goBack()">돌아가기</button>
    </p>
  </div>

  <script>
    function goAdventure() {
      const adventure_url = "{% url 'games:adventure_attack' %}";
      location.replace(adventure_url);
    }
    
    function goBack() {
      const url = "{% url 'games:adventure_home' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/adventure_home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
{% endblock %}

{% block body %}
  <div class="adventure">
    <h1>
      <div>
        {{character.nickname}}님,
      </div>
      <div>
        모험을 떠나보세요!
      </div>
    </h1>

    <p>당신은 <<{{weapon_name}}>> 무기를 갖고 있습니다.</p>
    <p><<{{weapon_name}}>>의 공격력은 {{weapon_power}}입니다.</p>

    <p>
      <img src="{% static 'images/cat_adventure_home.png' %}" alt="cat_adventure_home">
    </p>

    <p>
      <button onclick="goAdventure()">모험 떠나기</button>
    </p>
    <p>
      <button onclick="goWorkroom()">무기 공방</button>
    </p>
    <p>
      <button onclick="goBack()">게임 목록으로</button>
    </p>
  </div>

  <script>
    function goAdventure() {
      const adventure_url = "{% url 'games:adventure_attack' %}";
      location.href = adventure_url;
    }

    function goWorkroom() {
      const workroom_url = "{% url 'games:weapon_workroom' %}";
      location.href = workroom_url;
    }

    function goBack() {
      const url = "{% url 'games:game_list' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/adventure_new.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>{{user.character.nickname}}님의 모험을 시작합니다.</h1>

  <p>모험에 필요한 무기는 랜덤으로 선택됩니다.</p>
  <p><<{{random_weapon.name}}>> 무기가 선택되었습니다.</p>
  <p>이 무기를 받으시겠습니까?</p>

  <p>
    <button onclick="selectAgain()">다시 선택하기</button>
  </p>
  <form action="{% url 'games:weapon_get' %}" method="post">
    {% csrf_token %}
    <button type="submit" name="random-weapon" value="{{random_weapon.id}}">무기 받기</button>
  </form>

  <script>
    function selectAgain() {
      location.reload();
    }
  </script>

{% endblock %}

games/templates/games/character_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
{% endblock %}

{% block body %}
  <h1>캐릭터 생성</h1>
  
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      {{character_form}}
      <input type="submit" value="생성">
    </div>
  </form>
{% endblock %}

games/templates/games/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_list.css' %}">
{% endblock %}

{% block body %}
  <h1>게임 목록</h1>

  <ol class="game-list">
    <li><p><a href="{% url 'games:adventure_home'%}">장고캣의 모험</a></p></li>
    <li><p><a href="https://draw-it-friends.vercel.app/" target="_blank">그려줘 친구들!</a></p></li>
  </ol>
{% endblock %}

games/templates/games/lucky_item_change.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>무기 뽑기 결과</h1>

  {% include 'games/character_goods.html' %}

  <p><<{{random_lucky_item.default_lucky_item.name}}>> 아이템을 획득하였습니다!</p>
  {% if first %}
    <p>획득한 아이템은 인벤토리에서 확인할 수 있습니다.</p>
  {% elif upgrade %}
    <p>아이템이 업그레이드 되었습니다. 공격력이 증가하였습니다.</p>
  {% else %}
    <p>아이템이 최대 레벨({{random_lucky_item.level}})에 도달하였습니다.</p>
  {% endif %}

  <p>
    <form action="{% url 'games:weapon_pick' %}" method="post" onsubmit="return checkPick()">
      {% csrf_token %}
      {% if character.coin < 500 %}
        <button type="submit" class="disabled" disabled>무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 코인이 부족합니다.)</span>
        {% else %}
        <button type="submit">무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 무기를 교체하면 무기 레벨이 초기화됩니다.)</span>
      {% endif %}
    </form>
  </p>

  <p>
    <button onclick="goBack()">돌아가기</button>
  </p>

  <script>
    function alertSuccess() {
      alert('교체되었습니다.');
    }

    function checkPick() {
      const result = confirm("정말 뽑으시겠습니까?\n500코인이 소모됩니다.");
      return result;
    }

    function goBack() {
      const url = "{% url 'games:weapon_workroom' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/weapon_change.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>무기 뽑기 결과</h1>

  {% include 'games/character_goods.html' %}

  <p>당신이 뽑은 무기는 <<{{random_weapon.name}}>>입니다.</p>
  <p>교체하시겠습니까?</p>

  <p>
    <form action="{% url 'games:weapon_change' %}" method="post">
      {% csrf_token %}
      <button type="submit" name="random-weapon" value="{{random_weapon.id}}" onclick="alertSuccess()">교체하기</button>
      <span class="weapon-info">(※ 무기 레벨이 초기화됩니다.)</span>
    </form>
  </p>

  <p>
    <form action="{% url 'games:weapon_pick' %}" method="post" onsubmit="return checkPick()">
      {% csrf_token %}
      {% if character.coin < 500 %}
        <button type="submit" class="disabled" disabled>무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 코인이 부족합니다.)</span>
        {% else %}
        <button type="submit">무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 무기를 교체하면 무기 레벨이 초기화됩니다.)</span>
      {% endif %}
    </form>
  </p>

  <p>
    <button onclick="goBack()">돌아가기</button>
  </p>

  <script>
    function alertSuccess() {
      alert('교체되었습니다.');
    }

    function checkPick() {
      const result = confirm("정말 뽑으시겠습니까?\n500코인이 소모됩니다.");
      return result;
    }

    function goBack() {
      const url = "{% url 'games:weapon_workroom' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/weapon_upgrade.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>무기 강화</h1>

  {% include 'games/character_goods.html' %}

  <p>무기 강화에 {{result}}하였습니다.</p>
  {% if result == '성공' %}
    <p>무기의 레벨이 {{weapon_level}}(으)로 올라갑니다.</p>
    <p>무기의 공격력이 {{original_power}}(으)로 증가하였습니다.</p>
  {% endif %}
  
  <p>
    <button onclick="goBack()">돌아가기</button>
  </p>

  <script>
    function goBack() {
      const url = "{% url 'games:weapon_workroom' %}";
      location.replace(url);
    }
  </script>
{% endblock %}

games/templates/games/weapon_workroom.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/games/game_form.css' %}">
  <link rel="stylesheet" href="{% static 'css/games/game_adventure.css' %}">
  {% endblock %}

{% block body %}
  <h1>무기 공방</h1>
  
  {% include 'games/character_goods.html' %}
  
  <p>
    <form action="{% url 'games:weapon_pick' %}" method="post" onsubmit="return checkPick()">
      {% csrf_token %}
      {% if character.coin < 500 %}
        <button type="submit" class="disabled" disabled>무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 코인이 부족합니다.)</span>
        {% else %}
        <button type="submit">무기 뽑기(500코인)</button>
        <span class="weapon-info">(※ 무기를 교체하면 무기 레벨이 초기화됩니다.)</span>
      {% endif %}
    </form>
  </p>

  <p>
    <form action="{% url 'games:weapon_upgrade' %}" method="post" onsubmit="return checkUpgrade()">
      {% csrf_token %}
      {% if character.coin < required_coin %}
        <button type="submit" class="disabled" disabled>무기 강화하기(<span id="upgrade">{{required_coin}}코인</span>)</button>
        <span class="weapon-info">(※ 코인이 부족합니다.)</span>
        {% elif character.weapon.level >= 10 %}
        <button type="submit" class="disabled" disabled>무기 강화하기(<span id="upgrade">{{required_coin}}코인</span>)</button>
        <span class="weapon-info">(※ 강화 최대 레벨에 도달하였습니다.)</span>
      {% else %}
        <button type="submit">무기 강화하기(<span id="upgrade">{{required_coin}}코인</span>)</button>
        <span class="weapon-info">(※ 무기의 레벨이 높아질수록 강화 성공 확률이 낮아집니다.)</span>
        {% endif %}
    </form>
  </p>
  
  <p>
    <button onclick="goBack()">돌아가기</button>
  </p>

  <script>
    function checkPick() {
      const result = confirm("정말 뽑으시겠습니까?\n500코인이 소모됩니다.");
      return result;
    }

    function checkUpgrade() {
      const coin = document.getElementById('upgrade').innerText;
      const result = confirm("무기 강화에 실패할 수도 있습니다.\n정말 강화하시겠습니까?\n"+coin+"이 소모됩니다.");
      return result;
    }

    function goBack() {
      const url = "{% url 'games:adventure_home' %}";
      location.replace(url);
    }
  </script>
{% endblock %}