accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

djangocat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postings.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG == False:
    urlpatterns += re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
    path('adventure/attack/', views.adventure_attack, name='adventure_attack'),
    path('adventure/attack/result/', views.adventure_attack_result, name='adventure_attack_result'),
    path('weapon/workroom/', views.weapon_workroom, name='weapon_workroom'),
    path('weapon/pick/', views.weapon_pick, name='weapon_pick'),
    path('weapon/change/', views.weapon_change, name='weapon_change'),
    path('weapon/upgrade/', views.weapon_upgrade, name='weapon_upgrade'),
]

postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'

urlpatterns = [
    path('', views.index, name='index'),
    path('info/', views.information, name="information"),
    path('postings/', views.posting_list, name='posting_list'),
    path('posting/create/', views.posting_create, name='posting_create'),
    path('posting/<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('posting/<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('posting/<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    path('posting/<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('posting/admin/create/', views.posting_admin_create, name='posting_admin_create'),
    path('posting/admin/delete/', views.posting_admin_delete, name='posting_admin_delete'),
]

djangocat/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Cat</title>
  <link rel="icon" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <script src="https://kit.fontawesome.com/a1e1be19c8.js" crossorigin="anonymous"></script>
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="pc">
    <div class="navbar">
      <div class="navbar__page">
        <span>
          <a href="{% url 'postings:index' %}">
            <img class="navbar__logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
          </a>
        </span>
        <span>
          <a href="{% url 'postings:posting_list' %}">글목록</a>
        </span>
        <span>
          <a href="{% url 'postings:posting_create' %}">글쓰기</a>
        </span>
        <span>
          <a href="{% url 'games:game_list' %}">게임목록</a>
        </span>
      </div>
      <div class="navbar__account">
        {% if user.is_authenticated %}
        <span>
          {{user.username}}님 안녕하세요.
        </span>
        <span>
          <a href="{% url 'accounts:logout' %}" onclick="return userLogout()">로그아웃</a>
        </span>
        {% else %}
          <span>
            <a href="{% url 'accounts:login' %}">로그인</a>
          </span>
          <span>
            <a href="{% url 'accounts:signup' %}">회원가입</a>
          </span>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="mobile">
    <div class="navbar">
      <div class="navbar__page">
        <span>
          <a href="{% url 'postings:index' %}">
            <img class="navbar__logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
          </a>
        </span>
      </div>
      <div class="navbar__menu" onclick="openMenu()">
        <span id="menu-icon">
          <i class="fa-solid fa-bars fa-2x"></i>
        </span>
      </div>
    </div>
    <div id="navbar-hidden">
      <div class="navbar-side">
        {% if not user.is_authenticated%}
        <span>
          <a href="{% url 'accounts:signup' %}">회원가입</a>
        </span>
        <hr class="navbar__line">
        <span>
          <a href="{% url 'accounts:login' %}">로그인</a>
        </span>
        <hr class="navbar__line">
        {% endif %}
        <span>
          <a href="{% url 'postings:posting_list' %}">글목록</a>
        </span>
        {% if user.is_authenticated %}
        <hr class="navbar__line">
        <span>
          <a href="{% url 'postings:posting_create' %}">글쓰기</a>
        </span>
        {% endif %}
        <hr class="navbar__line">
        <span>
          <a href="{% url 'games:game_list' %}">게임목록</a>
        </span>
        {% if user.is_authenticated %}
        <hr class="navbar__line">
        <span>
          <a href="{% url 'accounts:logout' %}" onclick="return userLogout()">로그아웃</a>
        </span>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  <script>
    function userLogout() {
      const result = confirm("로그아웃 하시겠습니까?");
      return result;
    }

    let open_status = 0;
    function openMenu() {
      const menu_icon = document.getElementById("menu-icon");
      const navbar_hidden = document.getElementById("navbar-hidden");
      if (open_status == 0) {
        open_status = 1;
        menu_icon.innerHTML = '<i class="fa-solid fa-xmark fa-2x"></i>';
        navbar_hidden.setAttribute("style", "display: block;");
      }
      else {
        open_status = 0;
        menu_icon.innerHTML = '<i class="fa-solid fa-bars fa-2x"></i>';
        navbar_hidden.setAttribute("style", "display: none;");
      }
    }
  </script>
</body>
</html>